name: Daily Commit

on:
  schedule:
    - cron: "0 12 * * *"

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Auto commit
        run: |
          echo "$(date)" >> activity.log
          git config --global user.name "GitHub Bot"
          git config --global user.email "kollipunith@gmail.com"
          git add .
          git commit -m "Automated commit on $(date)" || exit 0
          git push
